demo/config/routes.rb
Demo::Application.routes.draw do

  
  
  
  root :to => "events#index"
  
 
  devise_for :consumers, :controllers => { :omniauth_callbacks => "consumers/omniauth_callbacks" }

  resources :events
  get "events/category/:page" => "events#category"

  match ':controller(/:action(/:id))(.:format)'

end

demo/app/models/consumer.rb
class Consumer < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  

  # Setup accessible (or protected) attributes for your model
  attr_accessible :email, :password, :password_confirmation, :remember_me, :provider, :uid, :name
  # attr_accessible :title, :body
  devise :database_authenticatable, :registerable, :recoverable, :rememberable, :trackable, :validatable, :omniauthable, :omniauth_providers => [:facebook]
  
  has_many :events  

  def self.find_for_facebook_oauth(auth, signed_in_resource=nil)
  consumer = Consumer.where(:provider => auth.provider, :uid => auth.uid).first
  unless consumer
    consumer = Consumer.create(name:auth.extra.raw_info.name,
                         provider:auth.provider,
                         uid:auth.uid,
                         email:auth.info.email,
                         password:Devise.friendly_token[0,20]
                         )
  end
  consumer
 end
 def self.new_with_session(params, session)
    super.tap do |consumer|
      if data = session["devise.facebook_data"] && session["devise.facebook_data"]["extra"]["raw_info"]
        consumer.email = data["email"] if consumer.email.blank?
      end
    end
  end
end

demo/app/models/event.rb
class Event < ActiveRecord::Base
  attr_accessible :description, :discussion, :name, :price, :pic, :pic_file_name, :pic_content_type, :pic_file_size, :pic_updated_at, :cate, :consumer_id, :buy_id
  validates_presence_of :name
  has_attached_file :pic, :styles => { :medium => "300x300>", :thumb => "100x100>"}  
  belongs_to :consumer
  def self.search(search)  
    if search  
      find(:all, :conditions => ['name LIKE ?', "%#{search}%"])  
    else  
      find(:all)  
    end  
  end  
end

demo/app/controllers/aboutus_controller.rb
class AboutusController < ApplicationController
def introduce
    end
end

demo/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

demo/app/controllers/consumers/omniauth_callbacks_controller.rb
class Consumers::OmniauthCallbacksController < Devise::OmniauthCallbacksController
  def facebook
    # You need to implement the method below in your model (e.g. app/models/consumer.rb)
    @consumer = Consumer.find_for_facebook_oauth(request.env["omniauth.auth"], current_consumer)
 
    if @consumer.persisted?
      sign_in_and_redirect @consumer, :event => :authentication #this will throw if @consumer is not activated
      set_flash_message(:notice, :success, :kind => "Facebook") if is_navigational_format?
    else
      session["devise.facebook_data"] = request.env["omniauth.auth"]
      redirect_to new_consumer_registration_url
    end
  end
end

demo/app/controllers/contactus_controller.rb
class ContactusController < ApplicationController
def contactinfo
    end
end

demo/app/controllers/events_controller.rb
class EventsController < ApplicationController

  def index
    @events = Event.all
    @events = Event.search(params[:search])  
    #page = params[:page]
    #if  page == '1'
    #@event = Event.where("cate='1'") 
    #elsif page == '2'
    #@event = Event.where("cate='2'") 
    #elsif page == '3'
    #@event = Event.where("cate='3'") 
    #end
  end

  def new
    @event = Event.new
  end

  def create
    @event = Event.new(params[:event])
    @event.save
    redirect_to :action => :index
  end

  def show
    @event = Event.includes(:consumer).find(params[:id])
    @page_title = @event.name
    
  end

  def edit
    @event = Event.find(params[:id])
  end

  def update
    @event = Event.find(params[:id])
    @event.update_attributes(params[:event])

    redirect_to :action => :show, :id => @event
  end

  def giveup
  redirect_to :action => :index
  end

  def destroy
  @event = Event.find(params[:id])
  @event.destroy
  redirect_to :action => :index
  end 
  
  
  
  def category
    @event = Event.all
    if  params[:page] == '1'
    @event = Event.where("cate='1'") 
    elsif params[:page] == '2'
    @event = Event.where("cate='2'") 
    elsif params[:page] == '3'
    @event = Event.where("cate='3'") 
    elsif  params[:page] == '4'
    @event = Event.where("cate='4'")
    elsif  params[:page] == '5'
    @event = Event.where("cate='5'") 
    elsif params[:page] == '0'
    @event = Event.all
    end
  end
  
  def buy

  @event = Event.find(params[:id])
  @event.update_attributes(:buy_id=>current_consumer.id)
  flash[:notice] = "Thanks for buying this product"
  redirect_to :action => :index
  end
  

  end 

demo/app/controllers/usermanagement_controller.rb
class UsermanagementController < ApplicationController
  
   def userprofile
   @event = Event.includes(:consumer).where( :consumer_id => current_consumer.id)

   @buy = Event.includes(:consumer).where( :buy_id => current_consumer.id)
   end
end

demo/app/helpers/aboutus_helper.rb
module AboutusHelper
end

demo/app/helpers/application_helper.rb
module ApplicationHelper
end

demo/app/helpers/contactus_helper.rb
module ContactusHelper
end

demo/app/helpers/event_helper.rb
module EventHelper
end

demo/app/helpers/events_helper.rb
module EventsHelper
end

demo/app/helpers/homepage_helper.rb
module HomepageHelper
end

demo/app/helpers/items_helper.rb
module ItemsHelper
end

demo/app/helpers/usermanagement_helper.rb
module UsermanagementHelper
end

demo/app/helpers/welcome_helper.rb
module WelcomeHelper
end

demo/app/views/aboutus/introduce.html.erb
<html>
<head>
<title>
</title>
</head>
<body>
<br>
<br>
<marquee><font size=6>Welcome to Supergirl's Closet</marquee>
<br>
<br>
<br>
<div id="aboutus">
<p><align=center><h3> This is a second hand product exchange website for girls. <br> We are students from Tsing Hua University. <br> Our group members are: <br>
</h3>
<li> Ana <br>
<li> Amber<br>
<li> Elaine <br>
<li> Karla <br>
 </li>
<br> <span><%= image_tag("intro.gif") %></span>


<img src="">
</body>
</div>
</html>

demo/app/views/consumers/shared/_links.erb
<%- if controller_name != 'sessions' %>
  <%= link_to "Sign in", new_session_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.registerable? && controller_name != 'registrations' %>
  <%= link_to "Sign up", new_registration_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.recoverable? && controller_name != 'passwords' && controller_name != 'registrations' %>
  <%= link_to "Forgot your password?", new_password_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.confirmable? && controller_name != 'confirmations' %>
  <%= link_to "Didn't receive confirmation instructions?", new_confirmation_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.lockable? && resource_class.unlock_strategy_enabled?(:email) && controller_name != 'unlocks' %>
  <%= link_to "Didn't receive unlock instructions?", new_unlock_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.omniauthable? %>
  <%- resource_class.omniauth_providers.each do |provider| %>
    <%= link_to "Sign in with #{provider.to_s.titleize}", omniauth_authorize_path(resource_name, provider) %><br />
  <% end -%>
<% end -%>

demo/app/views/contactus/contactinfo.html.erb
<script type="text/javascript">var servicedomain="www.123contactform.com"; var frmRef=''; try { frmRef=window.top.location.href; } catch(err) {}; var cfJsHost = (("https:" == document.location.protocol) ? "https://" : "http://"); document.write(unescape("%3Cscript src='" + cfJsHost + servicedomain + "/includes/easyXDM.min.js' type='text/javascript'%3E%3C/script%3E")); frmRef=encodeURIComponent(frmRef).replace('%26','[%ANDCHAR%]'); document.write(unescape("%3Cscript src='" + cfJsHost + servicedomain + "/jsform-818444.js?ref="+frmRef+"' type='text/javascript'%3E%3C/script%3E")); </script>

<br>
<br>
<p>Contact Supergirls --- kk03232003@gmail.com</p>

demo/app/views/events/category.html.erb
<br>
<br>
<div id="searchbar">
<br>
<%= form_tag events_path, :method => 'get' do %>  
  <p>  
    <%= text_field_tag :search, params[:search] %>  
    <%= submit_tag "Search", :name => nil %>
</p>
<% end %>
</div>
<br>
<div id="categorylist">
<br>
<FONT SIZE=2>
<h2>CATEGORIES</h2>
<br>
<FONT SIZE=3>
<a href="/events/category/1">Coats</a>
<FONT SIZE=3>&nbsp;&nbsp;
<br>
<a href="/events/category/2">Pants</a>
<FONT SIZE=3>&nbsp;&nbsp;
<br>
<a href="/events/category/3">Shoes</a>
<FONT SIZE=3>&nbsp;&nbsp;
<br>
<a href="/events/category/4">Accessory</a>
<FONT SIZE=3>&nbsp;&nbsp;
<br>
<a href="/events/category/5">other</a>
<br>
<br>
<br>
<br>
<br>
<br>
</div>
<br>
<br>
<% @event.each do |event| %>
<div id="products">
<%= event.name %>
<br>
<%= link_to( image_tag(event.pic.url(:medium)), :action => 'show', :id => "#{event.id}")%></br> 
<br> 
</div>
<% end %>

demo/app/views/events/edit.html.erb
<%= form_for @event, :url => { :controller => 'events', :action => 'update', :id => @event } do |f| %>
    <br>
<div id="itemeditbackground">
<br>
  <div id="itemedit">
  <h4 align=left>
    <%= f.label :name, "Procuct Name" %>
    <%= f.text_field :name, size: "25x10" %>
    <br>
    <%= f.select :cate, [['clothes','1'],['cosmetics','2'],['stationery','3'],['furniture','4'],['other','5']] %>
    <br>
    <%= f.label :price, "Price" %>
    <%= f.text_field :price, size: "25x10" %>
    <br>
    <br>
    
    <%= f.label :pic, "Product Pic." %>
    <%= f.file_field :pic, size: "10x10" %>
    <br>
    <br>
    <%= f.label :description, "Description" %>
    <br>
    <%= f.text_area :description %>
    <br>
    <br>
    <%= f.submit "Create" %>
    <%= f.submit "Giveup" %>
<% end %>
  </h4>
  </div>
</div>

demo/app/views/events/form.html.erb
<%= form_for(@item) do |f| %>
  <% if @item.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@item.errors.count, "error") %> prohibited this item from being saved:</h2>

      <ul>
      <% @item.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br />
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :price %><br />
    <%= f.number_field :price %>
  </div>
  <div class="field">
    <%= f.label :image %><br />
    <%= f.text_field :image %>
  </div>
  <div class="field">
    <%= f.label :description %><br />
    <%= f.text_area :description %>
  </div>
  <div class="field">
    <%= f.label :discussion %><br />
    <%= f.text_area :discussion %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

demo/app/views/events/index.html.erb
<br>
<br>
<div id=searchbar>         
<br>
<%= form_tag events_path, :method => 'get' do %>
  <p>  
    <%= text_field_tag :search, params[:search] %> 
    <%= submit_tag "Search", :name => nil %>
</p>
<br>
<% end %>

</div>
<div id="categorylist">
<br>
<FONT SIZE=2>
<h2>CATEGORIES</h2>
<br>
<FONT SIZE=3>
<a href="/events/category/1">Coats</a>
<FONT SIZE=3>&nbsp;&nbsp;
<br>
<a href="/events/category/2">Pants</a>
<FONT SIZE=3>&nbsp;&nbsp;
<br>
<a href="/events/category/3">Shoes</a>
<FONT SIZE=3>&nbsp;&nbsp;
<br>
<a href="/events/category/4">Accessory</a>
<FONT SIZE=3>&nbsp;&nbsp;
<br>
<a href="/events/category/5">other</a>
<br>
<br>
<br>
<br>
<br>
<br>
</div>
<ul><br>
<% @events.each do |event| %>


<% if current_consumer %>
  <% if event.consumer.id==current_consumer.id %>
    <% if event.buy_id == nil %>

   
    <FONT SIZE=3>


    
    <div id="products">
    <%= link_to( image_tag(event.pic.url(:medium)), :action => 'show', :id => "#{event.id}")%>
<br>
    <%= link_to 'Detail', event_path(event.id), :method=>:put %>
    <%= link_to 'Edit', :controller => 'events', :action => 'edit', :id => event %>
    <%= link_to 'Delete', event_path(event.id), :method=> :delete %>
    <br>    
    <%= event.name %>
    <br>
    <%='Price: NT'%>
    <%= event.price %>
    
    </div>

    <% else %>
 
    <div id="products">
   <%= link_to( image_tag(event.pic.url(:medium)), :action => 'show', :id => "#{event.id}")%>
    <br>
    <%= event.name %>
    <br>
    <%='Price: NT'%>
    <%= event.price %>
    <br>
    <%= 'Somebody want to buy this!'%>
    <FONT SIZE=3><%= link_to 'Add new item', :controller => 'events', :action => 'new' %>
    <% end %> </div>
  
<% else %>
    <% if event.buy_id == nil %>
    
    <div id="products">

    <%= link_to( image_tag(event.pic.url(:medium)), :action => 'show', :id => "#{event.id}")%>
    <%= event.name %>
    <br>
    <%='Price: NT'%>
    <%= event.price %>
    <FONT SIZE=3><%= link_to 'Add new item', :controller => 'events', :action => 'new' %>
    <br>
    <FONT SIZE=3></div>

    <% else %>
    
    <div id="products">
<%= link_to( image_tag(event.pic.url(:medium)), :action => 'show', :id => "#{event.id}")%>
    <br>
    <%= event.name %>
    <br>
    <%='Price: NT'%>
    <%= event.price %>
    <br>
    <%= 'Sorry, this item is booked' %>  
    <FONT SIZE=3><%= link_to 'Add new item', :controller => 'events', :action => 'new' %>
    <% end %> <FONT SIZE=3>
    <% end %></div>
<% else %>
    <div id="products">
    <%= event.name %>
    <br>
    <%='Price: NT'%>
    <%= event.price %>
    <br>
<%= link_to( image_tag(event.pic.url(:medium)), :action => 'show', :id => "#{event.id}")%>
<% end %>
</div>
<%end%>

<br>
<FONT SIZE=3><%= link_to 'Add new item', :controller => 'events', :action => 'new' %>  

demo/app/views/events/new.html.erb
<%= form_for @event, :url => { :controller => 'events', :action => 'create' } do |f| %>
<br>
<div id="itemeditbackground">
<br>
  <div id="itemedit">
  <h4 align=left>
    <%= f.label :name, "Procuct Name" %>
    <%= f.text_field :name, size: "25x10" %>
    <br>
    <br>
    <%= f.label :Cate, "Categories" %>
    <%= f.select :cate, [['Coats','1'],['Pants','2'],['Shoes','3'],['Accessory','4'],['other','5']] %>
    <br>
    <br>
    <%= f.label :price, "Price" %>
    <%= f.text_field :price, size: "25x10" %>
    <br>
    <br>
    
    <%= f.label :pic, "Product Pic." %>
    <%= f.file_field :pic, size: "10x10" %>
    <br>
    <br>
    <%= f.label :description, "Description" %>
    <br>
    <%= f.text_area :description %>
    <%= f.hidden_field :consumer_id, :value=>current_consumer.id %>
    <br>
    <br>
    <%= f.submit "Create" %>
    <%= f.submit "Giveup" %>
<% end %>
  </h4>
  </div>
</div>

demo/app/views/events/show.html.erb
<br>
<div id="categorylist">
<FONT SIZE=2>
<h2>CATEGORIES</h2>
<br>
<FONT SIZE=3>
<a href="/events/category/1">Coats</a>
<FONT SIZE=3>&nbsp;&nbsp;
<br>
<a href="/events/category/2">Pants</a>
<FONT SIZE=3>&nbsp;&nbsp;
<br>
<a href="/events/category/3">Shoes</a>
<FONT SIZE=3>&nbsp;&nbsp;

<br><a href="/events/category/4">Accessory</a>
<FONT SIZE=3>&nbsp;&nbsp;
<br>
<a href="/events/category/5">other</a>

</div>


<div id="hi">

<p>
<b>

<%= @event.name %></b>


</p>
<br/>
<p>
  <%= image_tag @event.pic.url(:medium) %>

</p>
<br/>
<p>
  Category: 
  <% case @event.cate %>
  <% when 1 %>
  <%= "Coats" %>
  <% when 2 %>
  <%= "Pants" %>
  <% when 3 %>
  <%= "Shoes" %>
  <% when 4 %>
  <%= "Accessory" %>
  <% when 5 %>
  <%= "other" %>
  <% end %>
</p>
<p>
  <b>Price:</b>
  <%= @event.price %>
</p>
</div>

<div id="description">
<h4 align=left>
<p>
  <b>Description:</b>
  <%= @event.description %>
<br>
<%= button_to 'I want to Buy', :controller => 'events', :action => 'buy',:id =>@event.id %>
<%= button_to 'Add to My Favorite', :controller => 'events', :action => 'favorite',:id =>@event.id %>
</p>  
</h4>
 
<br>
<br>
</div>	
<p>


<div id="discussion">
<h4 align=center>
  <b>Discussion:</b>
<br>
<br>
  <%= @event.discussion %>
<div class="fb-comments" data-width="1000" data-numposts="5" data-colorscheme="light"></div>
</p>
</h4>
</div>
<p><%= link_to 'Back to Index', :controller => 'events', :action => '' %></p>

demo/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title><%= @page_title || "Super Girls Closet" %></title>
  <title><%= @page_title || "Super Girls Closet!" %></title>
  <%= stylesheet_link_tag    "application" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>
<body>
<h2 align=left style="color: #FF6A6A">
<div id="header-wrapper">

	<div id="header" class="container">
		<div id="logo">
			<span><%= image_tag("super.jpg") %></span>
			
			 </div>
		</div>
		
	</div>
</div>
<div id="menu-wrapper">
		<div id="menu">
			<ul>
				<li><%= link_to 'Homepage', :controller => 'events', :action => 'index' %></a></li>
                                <li><%= link_to 'User Management', :controller => "usermanagement",:action => 'userprofile' %></li>
				<li><%= link_to 'Category', '/events/category/0', :method=>:get  %></li>
				<li><%= link_to 'About us', :controller => "aboutus",:action => 'introduce' %></li>
				<li><%= link_to 'Contact us', :controller => "contactus",:action => 'contactinfo' %></li>
                                
<% if current_consumer %>
    <li><%= link_to('LOG OUT', destroy_consumer_session_path, :method => :delete) %> |
    <%= link_to('CHANGE PWD', edit_registration_path(:consumer)) %> </li>
  <% else %>
    <li><%= link_to('REGISTER', new_registration_path(:consumer)) %> |
    <%= link_to('LOG IN', new_session_path(:consumer)) %> </li>
  <% end %>
			</ul>
		</div>
</div>
</h2>

<body align=center style="background: #ffffff;">
<h3 align=center style="color: #FF6A6A">
<%= yield %>
<div id="fb-root"></div>
<script>(function(d, s, id) {
  var js, fjs = d.getElementsByTagName(s)[0];
  if (d.getElementById(id)) return;
  js = d.createElement(s); js.id = id;
  js.src = "//connect.facebook.net/zh_TW/all.js#xfbml=1&appId=540259822730644";
  fjs.parentNode.insertBefore(js, fjs);
}(document, 'script', 'facebook-jssdk'));</script>
</h3>
</body>
</html>

demo/app/views/usermanagement/userprofile.html.erb
<b> Hello! </b>
<b>
<%=current_consumer.email %>
<br>
<br>
<div id="event">
<%='Your upload product list:' %>
<br>
<%@event.each do |event| %> 
<br>
<%=event.name %>
<br>
<br>
<%= image_tag event.pic.url(:medium) %>
<br>
<%= link_to 'Detail', event_path(event.id), :method=>:put %>
<%= link_to 'Edit', :controller => 'events', :action => 'edit', :id => event %>
<%= link_to 'Delete', event_path(event.id), :method=> :delete %> 
<br>

<br>

<%end%>
</div>

<div id="event">
<%= 'Your Favorite List' %>
<% @favorite.each do |event| %> 
<br>
<%if%>
<% event.favorite_id == current_consumer.id %>
<%=event.name %>
<br>
<%= image_tag event.pic.url(:medium) %>
<br>
<%= link_to 'Show', event_path(event.id), :method=>:put %>
<% end %>
</br>
<% end %>
</div>


<div id="event">
<%= 'Your Shopping List' %>
<% @buy.each do |event| %> 
<br>
<br>
<%if%>
<% event.id == current_consumer.id %>
<%=event.name %>
<br>
<%= image_tag event.pic.url(:medium) %>
<%end%>

</div>


</b>
<%end%>